set_property SRC_FILE_INFO {cfile:C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/constrs_1/imports/example_design/GTH_exdes.xdc rfile:../../../GTH_ex.srcs/constrs_1/imports/example_design/GTH_exdes.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC33 [get_ports DRP_CLK_IN_N]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB33 [get_ports DRP_CLK_IN_P]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y20 [get_cells GTH_support_i/GTH_init_i/inst/GTH_i/gt0_GTH_i/gthe2_i]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y21 [get_cells GTH_support_i/GTH_init_i/inst/GTH_i/gt1_GTH_i/gthe2_i]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W30 [get_ports rst_1]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W31 [get_ports rst_2]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N28 [get_ports TRACK_DATA_OUT]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC34 [get_ports clk]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB41 [get_ports tx_pin]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB42 [get_ports rx_pin]
