# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/loser/Desktop/gth_phase_ex/GTH_ex.srcs/sources_1/ip/FIFO/FIFO.xci
# IP: The module: 'FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/loser/Desktop/gth_phase_ex/GTH_ex.srcs/sources_1/ip/FIFO/FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/loser/Desktop/gth_phase_ex/GTH_ex.srcs/sources_1/ip/FIFO/FIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/loser/Desktop/gth_phase_ex/GTH_ex.srcs/sources_1/ip/FIFO/FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/loser/Desktop/gth_phase_ex/GTH_ex.srcs/sources_1/ip/FIFO/FIFO.xci
# IP: The module: 'FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/loser/Desktop/gth_phase_ex/GTH_ex.srcs/sources_1/ip/FIFO/FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/loser/Desktop/gth_phase_ex/GTH_ex.srcs/sources_1/ip/FIFO/FIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/loser/Desktop/gth_phase_ex/GTH_ex.srcs/sources_1/ip/FIFO/FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
