######################################################################
#
# File name : GTH_TB_wave.do
# Created on: Sat Aug 13 18:36:48 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
