######################################################################
#
# File name : GTH_TB_compile.do
# Created on: Sat Aug 13 18:36:22 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modesim\\win64\\vlib modelsim_lib/work
D:\\modesim\\win64\\vlib modelsim_lib/msim

D:\\modesim\\win64\\vlib modelsim_lib/msim/xil_defaultlib
D:\\modesim\\win64\\vlib modelsim_lib/msim/xpm
D:\\modesim\\win64\\vlib modelsim_lib/msim/fifo_generator_v13_2_1
D:\\modesim\\win64\\vlib modelsim_lib/msim/xbip_utils_v3_0_8
D:\\modesim\\win64\\vlib modelsim_lib/msim/axi_utils_v2_0_4
D:\\modesim\\win64\\vlib modelsim_lib/msim/xbip_pipe_v3_0_4
D:\\modesim\\win64\\vlib modelsim_lib/msim/xbip_dsp48_wrapper_v3_0_4
D:\\modesim\\win64\\vlib modelsim_lib/msim/xbip_dsp48_addsub_v3_0_4
D:\\modesim\\win64\\vlib modelsim_lib/msim/xbip_bram18k_v3_0_4
D:\\modesim\\win64\\vlib modelsim_lib/msim/mult_gen_v12_0_13
D:\\modesim\\win64\\vlib modelsim_lib/msim/floating_point_v7_0_14
D:\\modesim\\win64\\vlib modelsim_lib/msim/xbip_dsp48_mult_v3_0_4
D:\\modesim\\win64\\vlib modelsim_lib/msim/xbip_dsp48_multadd_v3_0_4
D:\\modesim\\win64\\vlib modelsim_lib/msim/div_gen_v5_1_12
D:\\modesim\\win64\\vlib modelsim_lib/msim/c_reg_fd_v12_0_4
D:\\modesim\\win64\\vlib modelsim_lib/msim/xbip_addsub_v3_0_4
D:\\modesim\\win64\\vlib modelsim_lib/msim/c_addsub_v12_0_11
D:\\modesim\\win64\\vlib modelsim_lib/msim/cordic_v6_0_13
D:\\modesim\\win64\\vlib modelsim_lib/msim/c_mux_bit_v12_0_4
D:\\modesim\\win64\\vlib modelsim_lib/msim/c_shift_ram_v12_0_11
D:\\modesim\\win64\\vlib modelsim_lib/msim/cmpy_v6_0_14
D:\\modesim\\win64\\vlib modelsim_lib/msim/xfft_v9_0_14

D:\\modesim\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
D:\\modesim\\win64\\vmap xpm modelsim_lib/msim/xpm
D:\\modesim\\win64\\vmap fifo_generator_v13_2_1 modelsim_lib/msim/fifo_generator_v13_2_1
D:\\modesim\\win64\\vmap xbip_utils_v3_0_8 modelsim_lib/msim/xbip_utils_v3_0_8
D:\\modesim\\win64\\vmap axi_utils_v2_0_4 modelsim_lib/msim/axi_utils_v2_0_4
D:\\modesim\\win64\\vmap xbip_pipe_v3_0_4 modelsim_lib/msim/xbip_pipe_v3_0_4
D:\\modesim\\win64\\vmap xbip_dsp48_wrapper_v3_0_4 modelsim_lib/msim/xbip_dsp48_wrapper_v3_0_4
D:\\modesim\\win64\\vmap xbip_dsp48_addsub_v3_0_4 modelsim_lib/msim/xbip_dsp48_addsub_v3_0_4
D:\\modesim\\win64\\vmap xbip_bram18k_v3_0_4 modelsim_lib/msim/xbip_bram18k_v3_0_4
D:\\modesim\\win64\\vmap mult_gen_v12_0_13 modelsim_lib/msim/mult_gen_v12_0_13
D:\\modesim\\win64\\vmap floating_point_v7_0_14 modelsim_lib/msim/floating_point_v7_0_14
D:\\modesim\\win64\\vmap xbip_dsp48_mult_v3_0_4 modelsim_lib/msim/xbip_dsp48_mult_v3_0_4
D:\\modesim\\win64\\vmap xbip_dsp48_multadd_v3_0_4 modelsim_lib/msim/xbip_dsp48_multadd_v3_0_4
D:\\modesim\\win64\\vmap div_gen_v5_1_12 modelsim_lib/msim/div_gen_v5_1_12
D:\\modesim\\win64\\vmap c_reg_fd_v12_0_4 modelsim_lib/msim/c_reg_fd_v12_0_4
D:\\modesim\\win64\\vmap xbip_addsub_v3_0_4 modelsim_lib/msim/xbip_addsub_v3_0_4
D:\\modesim\\win64\\vmap c_addsub_v12_0_11 modelsim_lib/msim/c_addsub_v12_0_11
D:\\modesim\\win64\\vmap cordic_v6_0_13 modelsim_lib/msim/cordic_v6_0_13
D:\\modesim\\win64\\vmap c_mux_bit_v12_0_4 modelsim_lib/msim/c_mux_bit_v12_0_4
D:\\modesim\\win64\\vmap c_shift_ram_v12_0_11 modelsim_lib/msim/c_shift_ram_v12_0_11
D:\\modesim\\win64\\vmap cmpy_v6_0_14 modelsim_lib/msim/cmpy_v6_0_14
D:\\modesim\\win64\\vmap xfft_v9_0_14 modelsim_lib/msim/xfft_v9_0_14

D:\\modesim\\win64\\vlog -64 -incr -sv -work xil_defaultlib  "+incdir+../../../../GTH_ex.srcs/sources_1/ip/CLK_RD" \
"D:/Vivado/Vivado/2017.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"D:/Vivado/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

D:\\modesim\\win64\\vcom -64 -93 -work xpm  \
"D:/Vivado/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd" \

D:\\modesim\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../GTH_ex.srcs/sources_1/ip/CLK_RD" \
"../../../../GTH_ex.srcs/sources_1/ip/ila_2/sim/ila_2.v" \
"../../../../GTH_ex.srcs/sources_1/ip/ila_1/sim/ila_1.v" \
"../../../../GTH_ex.srcs/sources_1/ip/ila_0/sim/ila_0.v" \

D:\\modesim\\win64\\vlog -64 -incr -work fifo_generator_v13_2_1  "+incdir+../../../../GTH_ex.srcs/sources_1/ip/CLK_RD" \
"../../../../GTH_ex.ip_user_files/ipstatic/simulation/fifo_generator_vlog_beh.v" \

D:\\modesim\\win64\\vcom -64 -93 -work fifo_generator_v13_2_1  \
"../../../../GTH_ex.ip_user_files/ipstatic/hdl/fifo_generator_v13_2_rfs.vhd" \

D:\\modesim\\win64\\vlog -64 -incr -work fifo_generator_v13_2_1  "+incdir+../../../../GTH_ex.srcs/sources_1/ip/CLK_RD" \
"../../../../GTH_ex.ip_user_files/ipstatic/hdl/fifo_generator_v13_2_rfs.v" \

D:\\modesim\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../GTH_ex.srcs/sources_1/ip/CLK_RD" \
"../../../../GTH_ex.srcs/sources_1/ip/FIFO/sim/FIFO.v" \

D:\\modesim\\win64\\vcom -64 -93 -work xbip_utils_v3_0_8  \
"../../../../GTH_ex.ip_user_files/ipstatic/hdl/xbip_utils_v3_0_vh_rfs.vhd" \

D:\\modesim\\win64\\vcom -64 -93 -work axi_utils_v2_0_4  \
"../../../../GTH_ex.ip_user_files/ipstatic/hdl/axi_utils_v2_0_vh_rfs.vhd" \

D:\\modesim\\win64\\vcom -64 -93 -work xbip_pipe_v3_0_4  \
"../../../../GTH_ex.ip_user_files/ipstatic/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \

D:\\modesim\\win64\\vcom -64 -93 -work xbip_dsp48_wrapper_v3_0_4  \
"../../../../GTH_ex.ip_user_files/ipstatic/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \

D:\\modesim\\win64\\vcom -64 -93 -work xbip_dsp48_addsub_v3_0_4  \
"../../../../GTH_ex.ip_user_files/ipstatic/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \

D:\\modesim\\win64\\vcom -64 -93 -work xbip_bram18k_v3_0_4  \
"../../../../GTH_ex.ip_user_files/ipstatic/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \

D:\\modesim\\win64\\vcom -64 -93 -work mult_gen_v12_0_13  \
"../../../../GTH_ex.ip_user_files/ipstatic/hdl/mult_gen_v12_0_vh_rfs.vhd" \

D:\\modesim\\win64\\vcom -64 -93 -work floating_point_v7_0_14  \
"../../../../GTH_ex.ip_user_files/ipstatic/hdl/floating_point_v7_0_vh_rfs.vhd" \

D:\\modesim\\win64\\vcom -64 -93 -work xbip_dsp48_mult_v3_0_4  \
"../../../../GTH_ex.ip_user_files/ipstatic/hdl/xbip_dsp48_mult_v3_0_vh_rfs.vhd" \

D:\\modesim\\win64\\vcom -64 -93 -work xbip_dsp48_multadd_v3_0_4  \
"../../../../GTH_ex.ip_user_files/ipstatic/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \

D:\\modesim\\win64\\vcom -64 -93 -work div_gen_v5_1_12  \
"../../../../GTH_ex.ip_user_files/ipstatic/hdl/div_gen_v5_1_vh_rfs.vhd" \

D:\\modesim\\win64\\vcom -64 -93 -work xil_defaultlib  \
"../../../../GTH_ex.srcs/sources_1/ip/phase_number/sim/phase_number.vhd" \
"../../../../GTH_ex.srcs/sources_1/ip/mult_gen_0/sim/mult_gen_0.vhd" \

D:\\modesim\\win64\\vcom -64 -93 -work c_reg_fd_v12_0_4  \
"../../../../GTH_ex.ip_user_files/ipstatic/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \

D:\\modesim\\win64\\vcom -64 -93 -work xbip_addsub_v3_0_4  \
"../../../../GTH_ex.ip_user_files/ipstatic/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \

D:\\modesim\\win64\\vcom -64 -93 -work c_addsub_v12_0_11  \
"../../../../GTH_ex.ip_user_files/ipstatic/hdl/c_addsub_v12_0_vh_rfs.vhd" \

D:\\modesim\\win64\\vcom -64 -93 -work cordic_v6_0_13  \
"../../../../GTH_ex.ip_user_files/ipstatic/hdl/cordic_v6_0_vh_rfs.vhd" \

D:\\modesim\\win64\\vcom -64 -93 -work xil_defaultlib  \
"../../../../GTH_ex.srcs/sources_1/ip/arctan/sim/arctan.vhd" \
"../../../../GTH_ex.srcs/sources_1/ip/multiplier/sim/multiplier.vhd" \

D:\\modesim\\win64\\vcom -64 -93 -work c_mux_bit_v12_0_4  \
"../../../../GTH_ex.ip_user_files/ipstatic/hdl/c_mux_bit_v12_0_vh_rfs.vhd" \

D:\\modesim\\win64\\vcom -64 -93 -work c_shift_ram_v12_0_11  \
"../../../../GTH_ex.ip_user_files/ipstatic/hdl/c_shift_ram_v12_0_vh_rfs.vhd" \

D:\\modesim\\win64\\vcom -64 -93 -work cmpy_v6_0_14  \
"../../../../GTH_ex.ip_user_files/ipstatic/hdl/cmpy_v6_0_vh_rfs.vhd" \

D:\\modesim\\win64\\vcom -64 -93 -work xfft_v9_0_14  \
"../../../../GTH_ex.ip_user_files/ipstatic/hdl/xfft_v9_0_vh_rfs.vhd" \

D:\\modesim\\win64\\vcom -64 -93 -work xil_defaultlib  \
"../../../../GTH_ex.srcs/sources_1/ip/FFT/sim/FFT.vhd" \

D:\\modesim\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../GTH_ex.srcs/sources_1/ip/CLK_RD" \
"../../../../GTH_ex.srcs/sources_1/ip/CLK_RD/CLK_RD_clk_wiz.v" \
"../../../../GTH_ex.srcs/sources_1/ip/CLK_RD/CLK_RD.v" \
"../../../../GTH_ex.srcs/sources_1/ip/GTH/GTH/example_design/gth_tx_startup_fsm.v" \
"../../../../GTH_ex.srcs/sources_1/ip/GTH/GTH/example_design/gth_rx_startup_fsm.v" \
"../../../../GTH_ex.srcs/sources_1/ip/GTH/gth_init.v" \
"../../../../GTH_ex.srcs/sources_1/ip/GTH/gth_cpll_railing.v" \
"../../../../GTH_ex.srcs/sources_1/ip/GTH/gth_gt.v" \
"../../../../GTH_ex.srcs/sources_1/ip/GTH/gth_multi_gt.v" \
"../../../../GTH_ex.srcs/sources_1/ip/GTH/GTH/example_design/gth_gtrxreset_seq.v" \
"../../../../GTH_ex.srcs/sources_1/ip/GTH/GTH/example_design/gth_rxpmarst_seq.v" \
"../../../../GTH_ex.srcs/sources_1/ip/GTH/GTH/example_design/gth_rxrate_seq.v" \
"../../../../GTH_ex.srcs/sources_1/ip/GTH/GTH/example_design/gth_sync_block.v" \
"../../../../GTH_ex.srcs/sources_1/ip/GTH/gth.v" \
"../../../../GTH_ex.srcs/sources_1/new/FIFO_ctrl.v" \
"../../../../GTH_ex.srcs/sources_1/new/FIFO_ctrl2.v" \
"../../../../GTH_ex.srcs/sources_1/new/compare.v" \
"../../../../GTH_ex.srcs/sources_1/new/cos_S1.v" \
"../../../../GTH_ex.srcs/sources_1/new/cos_S2.v" \
"../../../../GTH_ex.srcs/sources_1/imports/example_design/support/gth_common.v" \
"../../../../GTH_ex.srcs/sources_1/imports/example_design/support/gth_common_reset.v" \
"../../../../GTH_ex.srcs/sources_1/imports/example_design/gth_exdes.v" \
"../../../../GTH_ex.srcs/sources_1/imports/example_design/support/gth_gt_usrclk_source.v" \
"../../../../GTH_ex.srcs/sources_1/imports/example_design/support/gth_support.v" \
"../../../../GTH_ex.srcs/sources_1/new/phase_top.v" \
"../../../../GTH_ex.srcs/sim_1/imports/simulation/gth_tb.v" \

# compile glbl module
D:\\modesim\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

