# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/example_design/GTH_exdes.xdc

# IP: ip/phase_number/phase_number.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==phase_number || ORIG_REF_NAME==phase_number} -quiet] -quiet

# IP: ip/multiplier/multiplier.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multiplier || ORIG_REF_NAME==multiplier} -quiet] -quiet

# IP: ip/GTH/GTH.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==GTH || ORIG_REF_NAME==GTH} -quiet] -quiet
