# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath D:/modesim/win64
create_project -in_memory -part xc7vx690tffg1761-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.cache/wt [current_project]
set_property parent.project_path C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/imports/example_design/gt_rom_init_rx.dat
  C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/imports/example_design/gt_rom_init_tx.dat
}
read_verilog -library xil_defaultlib {
  C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/new/DDR3_CTRL.v
  C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/new/FFT_cal.v
  C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/new/FFT_modul_cal.v
  C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/new/FIFO_ctrl.v
  C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/new/FIFO_ctrl2.v
  C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/new/Output_wave.v
  C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/new/arctan_cal.v
  C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/new/compare.v
  C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/new/compare_cal.v
  C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/new/cos_S1.v
  C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/new/cos_S2.v
  C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/new/data_buff.v
  C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/new/ddr3_rw.v
  C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/imports/example_design/support/gth_common.v
  C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/imports/example_design/support/gth_common_reset.v
  C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/imports/example_design/support/gth_gt_usrclk_source.v
  C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/imports/example_design/support/gth_support.v
  C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/new/phase_cal.v
  C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/new/phase_top.v
  C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/new/signal_cor.v
  C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/new/uart_rx.v
  C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/new/uart_top.v
  C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/new/uart_tx.v
  C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/imports/example_design/gth_exdes.v
}
read_ip -quiet C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/phase_number/phase_number.xci
set_property used_in_implementation false [get_files -all c:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/phase_number/phase_number_ooc.xdc]

read_ip -quiet C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/multiplier/multiplier.xci
set_property used_in_implementation false [get_files -all c:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/multiplier/multiplier_ooc.xdc]

read_ip -quiet C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/GTH/GTH.xci
set_property used_in_implementation false [get_files -all c:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/GTH/GTH.xdc]
set_property used_in_implementation false [get_files -all c:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/GTH/GTH_ooc.xdc]

read_ip -quiet C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/CLK_RD/CLK_RD.xci
set_property used_in_implementation false [get_files -all c:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/CLK_RD/CLK_RD_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/CLK_RD/CLK_RD.xdc]
set_property used_in_implementation false [get_files -all c:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/CLK_RD/CLK_RD_ooc.xdc]

read_ip -quiet C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/FIFO/FIFO.xci
set_property used_in_implementation false [get_files -all c:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/FIFO/FIFO.xdc]
set_property used_in_implementation false [get_files -all c:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/FIFO/FIFO_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/FIFO/FIFO_ooc.xdc]

read_ip -quiet C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/FFT/FFT.xci
set_property used_in_implementation false [get_files -all c:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/FFT/FFT_ooc.xdc]

read_ip -quiet C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/arctan/arctan.xci
set_property used_in_implementation false [get_files -all c:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/arctan/arctan_ooc.xdc]

read_ip -quiet C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/mult_gen_0/mult_gen_0_ooc.xdc]

read_ip -quiet C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all c:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]

read_ip -quiet C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/mig_7series_0/mig_7series_0.xci
set_property used_in_implementation false [get_files -all c:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc]

read_ip -quiet C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/ila_1_1/ila_1.xci
set_property used_in_synthesis false [get_files -all c:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/ila_1_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/ila_1_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/ila_1_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/sources_1/ip/ila_1_1/ila_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/constrs_1/imports/example_design/GTH_exdes.xdc
set_property used_in_implementation false [get_files C:/Users/loser/Desktop/gth_phase_2G_DDR_youhua/GTH_ex.srcs/constrs_1/imports/example_design/GTH_exdes.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top GTH_exdes -part xc7vx690tffg1761-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef GTH_exdes.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file GTH_exdes_utilization_synth.rpt -pb GTH_exdes_utilization_synth.pb"
