# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/loser/Desktop/gth_phase_2G_DDR/GTH_ex.srcs/sources_1/ip/CLK_RD/CLK_RD.xci
# IP: The module: 'CLK_RD' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/loser/Desktop/gth_phase_2G_DDR/GTH_ex.srcs/sources_1/ip/CLK_RD/CLK_RD_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_RD'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/loser/Desktop/gth_phase_2G_DDR/GTH_ex.srcs/sources_1/ip/CLK_RD/CLK_RD.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_RD'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/loser/Desktop/gth_phase_2G_DDR/GTH_ex.srcs/sources_1/ip/CLK_RD/CLK_RD_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_RD'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/loser/Desktop/gth_phase_2G_DDR/GTH_ex.srcs/sources_1/ip/CLK_RD/CLK_RD.xci
# IP: The module: 'CLK_RD' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/loser/Desktop/gth_phase_2G_DDR/GTH_ex.srcs/sources_1/ip/CLK_RD/CLK_RD_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_RD'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/loser/Desktop/gth_phase_2G_DDR/GTH_ex.srcs/sources_1/ip/CLK_RD/CLK_RD.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_RD'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/loser/Desktop/gth_phase_2G_DDR/GTH_ex.srcs/sources_1/ip/CLK_RD/CLK_RD_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_RD'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
