# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/loser/Desktop/gth_phase_ex/GTH_ex.srcs/sources_1/ip/arctan/arctan.xci
# IP: The module: 'arctan' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/loser/Desktop/gth_phase_ex/GTH_ex.srcs/sources_1/ip/arctan/arctan_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arctan'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/loser/Desktop/gth_phase_ex/GTH_ex.srcs/sources_1/ip/arctan/arctan.xci
# IP: The module: 'arctan' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/loser/Desktop/gth_phase_ex/GTH_ex.srcs/sources_1/ip/arctan/arctan_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arctan'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
